// Generated by build.py!
//
// Contains unique build info (useful for tracking the version people are using!)
namespace NEP.Hitmarkers
{
    static partial class BuildInfo
    {
		public const int Epoch = 1719889144;
		public const string GitCommit = "54ec03ca7df35d7e813aab729b0223b679063351";
    }
}